name: EC2 배포 ## 워크플로우 이름

on: ## 실행 트리거
  push:
    branches:
      - main ## main 브랜치에 푸시될 때

jobs:
  deploy:
    runs-on: ubuntu-latest ## 실행 환경

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node 설정
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 의존성 설치
        run: npm ci

      - name: 빌드
        run: npm run build

      - name: EC2로 복사
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: .next,public,package.json,package-lock.json
          target: /var/www/my-app/

      - name: EC2에서 실행zz (pm2 사용)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /var/www/my-app
            npm install
            sudo npm install -g pm2 # pm2 전역 설치 (이미 설치되어 있다면 건너뛰어짐)
            pm2 start npm --name "your-app" -- start # npm start 명령어 실행 및 "your-app" 이름으로 pm2에 등록
            pm2 save # 현재 실행 중인 프로세스 목록 저장 (서버 재부팅 시 자동 실행)
            sudo pm2 startup systemd -u ${{ secrets.EC2_USER }} --hp /home/${{ secrets.EC2_USER }} # 서버 부팅 시 pm2 자동 시작 설정