name: EC2 Deploy with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 and run Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Docker 설치 (이미 설치되어 있다면 이 부분은 건너뛰어짐)
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker

            # 현재 사용자를 docker 그룹에 추가
            sudo usermod -aG docker $USER

            # 그룹 변경 적용 (또는 EC2 서버에 재접속)
            newgrp docker

            # 도커 실행
            docker pull seaproject/my-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 3000:3000 seaproject/my-app:latest
            docker system prune -a -f