name: EC2 Deploy with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 and run Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull seaproject/my-app:latest # 최신 이미지 pull
            docker stop my-app || true  # 기존 컨테이너 중지 (에러 무시)
            docker rm my-app || true    # 기존 컨테이너 삭제 (에러 무시)
            docker run -d --name my-app -p 3000:3000 seaproject/my-app:latest # 새 컨테이너 실행
            docker system prune -a -f # 안쓰는 이미지/컨테이너 정리