name: EC2 Deploy with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # v4로 업데이트

      - name: SSH into EC2 and setup Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Docker 설치 (이미 설치되어 있다면 이 부분은 건너뛰어짐)
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER  # 현재 사용자를 docker 그룹에 추가
            newgrp docker  # 그룹 변경 적용

      - name: SSH into EC2 and run Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 최신 이미지 pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest  # latest 태그 사용
            
            # 기존 컨테이너 중지 및 삭제
            docker stop my-container || true  # 에러 무시
            docker rm my-container || true    # 에러 무시
            
            # 새 컨테이너 실행
            docker run -d --name my-container -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest