name: EC2 배포 ## 워크플로우 이름

on: ## 실행 트리거
  push:
    branches:
      - main ## main 브랜치에 푸시될 때

jobs:
  deploy:
    runs-on: ubuntu-latest ## 실행 환경

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node 설정
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 의존성 설치
        run: npm ci

      - name: 빌드
        run: npm run build

      - name: EC2로 복사
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: .next,public,package.json,package-lock.json
          target: /var/www/my-app/

      - name: EC2에서 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /var/www/my-app
            npm install
            npm start